[features]
seeds = false
skip-lint = false

[programs.devnet]
soap_program = "soap4c4g3L9vQUQYSCJxhTbHdJYSiX3aZPzPGnp2CoN"

[programs.mainnet]
soap_program = "soap4c4g3L9vQUQYSCJxhTbHdJYSiX3aZPzPGnp2CoN"

[provider]
cluster = "devnet"
# wallet = "/Users/nagy/.config/solana/id.json"
wallet = "/Users/nagy/Desktop/Files/Dev3/SOAP/soap-portal/secret/aquaZKhcuUU1KetKdzNzumpbzEvcyHMqbkyysnMjMWr.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"