[toolchain]
#anchor_version = "0.26.0"
#anchor_version = "0.30.1"
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.18.17" # Solana version to use

[features]
resolution = true
skip-lint = false

[programs.devnet]
soap_program = "soap4c4g3L9vQUQYSCJxhTbHdJYSiX3aZPzPGnp2CoN"

[programs.mainnet]
soap_program = "AvpSYxeEiRdkFUYoKXCAn9jHfZVR51uQFSc18qV2u1Dj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/nagy/Desktop/Files/Dev3/SOAP/soap-portal/secret/aquaZKhcuUU1KetKdzNzumpbzEvcyHMqbkyysnMjMWr.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
