[features]
seeds = false
skip-lint = false
[programs.devnet]
soap_program = "4UMGtsE5ezGvj3nCJzg3icMuVmGkXHqmBniJHjfNaeBt"

[provider]
cluster = "Devnet"
wallet = "/Users/yusuf/.config/solana/id.json"
# wallet = "/Users/nagy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
