[features]
seeds = false
skip-lint = false
[programs.devnet]
soap_program = "oJCUBLbGJUUjZcuKVyjLmhLUo6zpkdDFvt2UCR3HWru"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/yusuf/.config/solana/id.json"
# wallet = "/Users/nagy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
